name = "epao"
compatibility_date = "2026-05-09"
compatibility_flags = ["global_fetch_strictly_public"]
pages_build_output_dir = "dist"

[observability]
enabled = true

[triggers]
crons = []

[[d1_databases]]
binding = "DB"
database_name = "epao"
database_id = "fa7c002e-e748-4783-bb8c-6c0758b020ca"
preview_database_id = "DB"

[[kv_namespaces]]
binding = "SESSION"
id = "8bfd9bdfdcd549019fbcab7442fc6ccd"
preview_id = "b91f5e0c3f41448895d111d1607c5c65"